package Acciones;


/**
* Acciones/Movimientos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Acciones.idl
* jueves 26 de mayo de 2016 12:02:55 AM CDT
*/

public final class Movimientos implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String nombre = null;
  public String apellidos = null;
  public String noCuenta = null;
  public String operacion = null;
  public String fecha = null;
  public String hora = null;

  public Movimientos ()
  {
  } // ctor

  public Movimientos (int _id, String _nombre, String _apellidos, String _noCuenta, String _operacion, String _fecha, String _hora)
  {
    id = _id;
    nombre = _nombre;
    apellidos = _apellidos;
    noCuenta = _noCuenta;
    operacion = _operacion;
    fecha = _fecha;
    hora = _hora;
  } // ctor

} // class Movimientos
