package Acciones;

/**
* Acciones/MovimientosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Acciones.idl
* jueves 26 de mayo de 2016 12:02:55 AM CDT
*/

public final class MovimientosHolder implements org.omg.CORBA.portable.Streamable
{
  public Acciones.Movimientos value = null;

  public MovimientosHolder ()
  {
  }

  public MovimientosHolder (Acciones.Movimientos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Acciones.MovimientosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Acciones.MovimientosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Acciones.MovimientosHelper.type ();
  }

}
