/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaServer;

import BD.EmpladoServidor;
import DatosServer.DtsEmpleadoServer;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedInputStream;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Skynet
 */
public class VRegistrar extends javax.swing.JFrame {
    String ruta; //Ruta de la imagen a cargar
    /**
     * Creates new form Registrar
     */
    EmpladoServidor opDs;
    DtsEmpleadoServer dts = new DtsEmpleadoServer();
    DefaultTableModel modelo;
    public VRegistrar() {        
        initComponents();
        opDs= new EmpladoServidor();        
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlLLenarDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtClaveEmpleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRegistroEmpleado = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarBy = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtPasswd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Empleado");

        pnlLLenarDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Rellene los datos solicitados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 11))); // NOI18N

        jLabel2.setText("*Clave Empleado:");

        txtClaveEmpleado.setText("223");

        jLabel3.setText("*Nombre:");

        lblFoto.setBackground(new java.awt.Color(204, 255, 204));
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("Foto");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("*Apellidos:");

        jLabel6.setText("Direccion:");

        jLabel7.setText("Telefono:");

        jLabel8.setText("*Usuario:");

        jLabel9.setText("*Contraseña:");

        jtRegistroEmpleado = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex,int columIndex)
            {
                return false;
            }
        };
        jtRegistroEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtRegistroEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtRegistroEmpleado.setRowHeight(50);
        jtRegistroEmpleado.getTableHeader().setReorderingAllowed(false);
        jtRegistroEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtRegistroEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtRegistroEmpleado);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel10.setText("Buscar:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel11.setText("Cargar Foto");

        javax.swing.GroupLayout pnlLLenarDatosLayout = new javax.swing.GroupLayout(pnlLLenarDatos);
        pnlLLenarDatos.setLayout(pnlLLenarDatosLayout);
        pnlLLenarDatosLayout.setHorizontalGroup(
            pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLLenarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlLLenarDatosLayout.createSequentialGroup()
                        .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlLLenarDatosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClaveEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLLenarDatosLayout.createSequentialGroup()
                                .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLLenarDatosLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(pnlLLenarDatosLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(9, 9, 9)))
                                    .addGroup(pnlLLenarDatosLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(10, 10, 10)))
                                .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtApellidos)
                                    .addGroup(pnlLLenarDatosLayout.createSequentialGroup()
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addGap(8, 8, 8)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPasswd, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                            .addGroup(pnlLLenarDatosLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarBy, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLLenarDatosLayout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLLenarDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(33, 33, 33))
        );
        pnlLLenarDatosLayout.setVerticalGroup(
            pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLLenarDatosLayout.createSequentialGroup()
                .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblFoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLLenarDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtClaveEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar)
                        .addComponent(btnActualizar)
                        .addComponent(btnGuardar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLLenarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtBuscarBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlLLenarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLLenarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static void main(String[] args) {
        new VRegistrar().setVisible(true);
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (dtsRequeridos()) 
        {
            dts.setIdEmpelado(txtClaveEmpleado.getText());
            dts.setNombre(txtNombre.getText());
            dts.setApellidos(txtApellidos.getText());
            dts.setDireccion(txtDireccion.getText());
            dts.setTelefono(txtTelefono.getText());
            dts.setNomUsuario(txtUsuario.getText());
            dts.setPasswd(txtPasswd.getText());
            try {
            File f = new File(ruta);                
            int len=(int) f.length();
            FileInputStream fis = new FileInputStream(f);
            byte[] img = new byte[len];
            BufferedInputStream bis = new BufferedInputStream(fis);
            bis.read(img);
            ByteArrayInputStream bais = new ByteArrayInputStream(img);
            dts.setImagen(bais);
            dts.setTamImagen(len);
                if (opDs.setEmpleadoServidor(dts)) {
                    JOptionPane.showMessageDialog(rootPane, "Se realizo la operacion con exito");
                    limpiarTabla();
                    llenarTabla();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo realizar la operacion");
                }

            } catch (Exception e) {
            }

            
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtRegistroEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtRegistroEmpleadoMouseClicked
        txtClaveEmpleado.setText((String) jtRegistroEmpleado.getValueAt(jtRegistroEmpleado.getSelectedRow(), 0));
        txtNombre.setText((String) jtRegistroEmpleado.getValueAt(jtRegistroEmpleado.getSelectedRow(), 1));
        txtApellidos.setText((String) jtRegistroEmpleado.getValueAt(jtRegistroEmpleado.getSelectedRow(), 2));
        txtDireccion.setText((String) jtRegistroEmpleado.getValueAt(jtRegistroEmpleado.getSelectedRow(), 3));
        txtTelefono.setText((String) jtRegistroEmpleado.getValueAt(jtRegistroEmpleado.getSelectedRow(), 4));
        txtUsuario.setText((String) jtRegistroEmpleado.getValueAt(jtRegistroEmpleado.getSelectedRow(), 5));
        txtPasswd.setText((String) jtRegistroEmpleado.getValueAt(jtRegistroEmpleado.getSelectedRow(), 6));
        ImageIcon imgIcon = (ImageIcon) jtRegistroEmpleado.getValueAt(jtRegistroEmpleado.getSelectedRow(), 7);
        lblFoto.setText(null);
        lblFoto.setIcon(imgIcon);
    }//GEN-LAST:event_jtRegistroEmpleadoMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
                if (dtsRequeridos()) 
        {
            dts.setIdEmpelado(txtClaveEmpleado.getText());
            dts.setNombre(txtNombre.getText());
            dts.setApellidos(txtApellidos.getText());
            dts.setDireccion(txtDireccion.getText());
            dts.setTelefono(txtTelefono.getText());
            dts.setNomUsuario(txtUsuario.getText());
            dts.setPasswd(txtPasswd.getText());
            try {
            File f = new File(ruta);                
            int len=(int) f.length();
            FileInputStream fis = new FileInputStream(f);
            byte[] img = new byte[len];
            BufferedInputStream bis = new BufferedInputStream(fis);
            bis.read(img);
            ByteArrayInputStream bais = new ByteArrayInputStream(img);
            dts.setImagen(bais);
            dts.setTamImagen(len);
                if (opDs.updateEmpleadoServidor(dts)) {
                    JOptionPane.showMessageDialog(rootPane, "Se realizo la operacion con exito");
                    limpiarTabla();
                    llenarTabla();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo realizar la operacion");
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtClaveEmpleado.getText().equals("")) {
            txtClaveEmpleado.setBackground(Color.red);
            txtClaveEmpleado.requestFocus();
            return;
        }
        dts.setIdEmpelado(txtClaveEmpleado.getText());
        if (opDs.deleteEmpleadoServidor(dts)) {
            JOptionPane.showMessageDialog(rootPane, "Se realizo la operacion con exito");
            limpiarTabla();
            llenarTabla();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo realizar la operacion");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtBuscarBy.getText().equals("")) {
            txtBuscarBy.setBackground(Color.red);
            txtBuscarBy.requestFocus();
            return;
        }
        limpiarTabla();
        modelo=opDs.getEmpleadoServerBy(txtBuscarBy.getText());
        jtRegistroEmpleado.setModel(modelo);
        
    }//GEN-LAST:event_btnBuscarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtRegistroEmpleado;
    public javax.swing.JLabel lblFoto;
    private javax.swing.JPanel pnlLLenarDatos;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtBuscarBy;
    public javax.swing.JTextField txtClaveEmpleado;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JPasswordField txtPasswd;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    //FUNCION QUE PERMITE ESTABLCER
    boolean dtsRequeridos() {
        if (txtClaveEmpleado.getText().equals("")) {
            txtClaveEmpleado.setBackground(Color.red);
            txtClaveEmpleado.requestFocus();
            return false;
        }
        if (txtNombre.getText().equals("")) {
            txtNombre.setBackground(Color.red);
            txtNombre.requestFocus();
            return false;
        }
        if (txtApellidos.getText().equals("")) {
            txtApellidos.setBackground(Color.red);
            txtApellidos.requestFocus();
            return false;
        }
        if (txtUsuario.getText().equals("")) {
            txtUsuario.setBackground(Color.red);
            txtUsuario.requestFocus();
            return false;
        }
        if (txtPasswd.getText().equals("")) {
            txtPasswd.setBackground(Color.yellow);
            txtPasswd.requestFocus();
            return false;
        }
        if (ruta == null) {
            lblFoto.setForeground(Color.red);            
            JOptionPane.showMessageDialog(null, "Debe Cargar una imagen");
            cargarImagen();
            return false;
        }
        return true;
    }
    //CARGAR UNA IMAGEN DESDE EL BUSCADOR DE ARCHIVOS
    void cargarImagen() 
    {
        final JFileChooser elegirImagen = new JFileChooser();
        elegirImagen.addChoosableFileFilter(new FileNameExtensionFilter("Img (*.*)", "jpg", "png", "gif", "bmp"));
        elegirImagen.setMultiSelectionEnabled(false);
        int o = elegirImagen.showOpenDialog(this);
        if (o == JFileChooser.APPROVE_OPTION) {
            ruta = elegirImagen.getSelectedFile().getAbsolutePath();
            Image preview = Toolkit.getDefaultToolkit().getImage(ruta);
            if (preview != null) {
                lblFoto.setText(null);
                ImageIcon icon = new ImageIcon(preview.getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
                lblFoto.setIcon(icon);
            }
        }
    }
    void llenarTabla()
    {
        modelo = opDs.getEmpleadoServer();
     jtRegistroEmpleado.setModel(modelo);
    }
    void limpiarTabla()
    {
        while(jtRegistroEmpleado.getRowCount()>0) modelo.removeRow(0);
    }
    
}
