package Acciones;


/**
* Acciones/bitsImgHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Acciones.idl
* jueves 26 de mayo de 2016 12:02:52 AM CDT
*/


//declaramos un arreglo para los bists de la imagen
public final class bitsImgHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public bitsImgHolder ()
  {
  }

  public bitsImgHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Acciones.bitsImgHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Acciones.bitsImgHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Acciones.bitsImgHelper.type ();
  }

}
