package Acciones;


/**
* Acciones/liClienteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Acciones.idl
* jueves 26 de mayo de 2016 12:02:52 AM CDT
*/


//creamos una lista de tipo Cliente
public final class liClienteHolder implements org.omg.CORBA.portable.Streamable
{
  public Acciones.Cliente value[] = null;

  public liClienteHolder ()
  {
  }

  public liClienteHolder (Acciones.Cliente[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Acciones.liClienteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Acciones.liClienteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Acciones.liClienteHelper.type ();
  }

}
