package Acciones;


/**
* Acciones/liClienteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Acciones.idl
* jueves 26 de mayo de 2016 12:02:52 AM CDT
*/


//creamos una lista de tipo Cliente
abstract public class liClienteHelper
{
  private static String  _id = "IDL:Acciones/liCliente:1.0";

  public static void insert (org.omg.CORBA.Any a, Acciones.Cliente[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Acciones.Cliente[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Acciones.ClienteHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Acciones.liClienteHelper.id (), "liCliente", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Acciones.Cliente[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Acciones.Cliente value[] = null;
    int _len0 = istream.read_long ();
    value = new Acciones.Cliente[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Acciones.ClienteHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Acciones.Cliente[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Acciones.ClienteHelper.write (ostream, value[_i0]);
  }

}
